backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images

collections:
  # Blog
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", hint:"" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
  # Gallery
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Image", name: "image", widget: allow_multiple: true, "image", multiple: true, required: true }